services:
  telegram-bot:
    build: .
    container_name: sesionstring_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./sessions:/app/sessions
      - ./downloads:/app/downloads
      
