services:
  telegram-bot:
    build: .
    container_name: sesionstring_bot
    restart: unless-stopped
    volumes:
      # Mantiene a salvo tus sesiones y descargas si el contenedor se reinicia o actualiza
      - ./sessions:/app/sessions
      - ./downloads:/app/downloads
